'use client';
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {supabase} from '../lib/supabase-browser';

const modules={dashboard:'Dashboard',employees:'Employees',companies:'Companies',contacts:'Contacts',projects:'Projects',pipeline:'Pipeline',followups:'Follow-ups',contracts:'Contracts',collections:'Collections',kpis:'KPIs',reports:'Reports'};
const stages=['lead','pricing','technical','tender','on_hand','negotiation','won','contract','collection','closed','lost'];
const activityTypes=['call','meeting','visit','email','whatsapp','tender_follow_up','technical_follow_up','commercial_follow_up','other'];
const empty={employee:{full_name:'',email:'',phone:'',job_title:''},company:{name:'',sector:'',company_type:'',city:'',phone:'',email:'',website:'',notes:''},contact:{company_id:'',full_name:'',position:'',mobile:'',email:'',contact_role:'',notes:''},project:{project_name:'',company_id:'',contact_id:'',employee_id:'',sector:'',project_type:'',scope:'',consultant:'',key_person:'',location:'',area:'',expected_value:'',stage:'lead'},activity:{project_id:'',activity_type:'meeting',subject:'',description:'',outcome:'',next_follow_up_date:'',next_action:''},contract:{project_id:'',contract_number:'',contract_date:'',contract_value:'',notes:''},schedule:{project_id:'',description:'',due_date:'',amount:''},payment:{project_id:'',collection_schedule_id:'',payment_date:'',amount:'',reference:'',notes:''},kpi:{employee_id:'',name:'Sales Target',target_value:'',weight:'',period_start:'',period_end:''}};

export default function Home(){
 const router=useRouter(); const [profile,setProfile]=useState(null); const [tab,setTab]=useState('dashboard'); const [lang,setLang]=useState('en'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [data,setData]=useState({profiles:[],companies:[],contacts:[],projects:[],activities:[],contracts:[],schedules:[],payments:[],kpis:[]}); const [modal,setModal]=useState(null); const [form,setForm]=useState({}); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState('');
 const t=useMemo(()=>lang==='ar'?{Dashboard:'لوحة التحكم',Employees:'الموظفون',Companies:'الشركات',Contacts:'جهات الاتصال',Projects:'المشاريع',Pipeline:'مسار المبيعات','Follow-ups':'المتابعات',Contracts:'العقود',Collections:'التحصيلات',KPIs:'مؤشرات الأداء',Reports:'التقارير',Add:'إضافة',Save:'حفظ',Cancel:'إلغاء',Search:'بحث',Logout:'تسجيل الخروج',Active:'نشط',NoData:'لا توجد بيانات بعد',Expected:'القيمة المتوقعة',Contract:'قيمة العقد',Collected:'المحصل',Remaining:'المتبقي'}:{Dashboard:'Dashboard',Employees:'Employees',Companies:'Companies',Contacts:'Contacts',Projects:'Projects',Pipeline:'Pipeline','Follow-ups':'Follow-ups',Contracts:'Contracts',Collections:'Collections',KPIs:'KPIs',Reports:'Reports',Add:'Add',Save:'Save',Cancel:'Cancel',Search:'Search',Logout:'Logout',Active:'Active',NoData:'No data yet',Expected:'Expected Value',Contract:'Contract Value',Collected:'Collected',Remaining:'Remaining'} ,[lang]);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data:p,error:e}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(e){setError(e.message);setLoading(false);return}if(!p||!p.is_active){await supabase.auth.signOut();router.replace('/login');return}setProfile(p);setLang(localStorage.getItem('emdad_lang')||'en');await load(p);setLoading(false)})()},[]);
 async function load(p=profile){setError('');const isAdmin=p?.role==='admin';const queries={profiles:supabase.from('profiles').select('*').order('full_name'),companies:supabase.from('companies').select('*').order('name'),contacts:supabase.from('contacts').select('*,companies(name)').order('full_name'),projects:supabase.from('projects').select('*,companies(name),profiles:employee_id(full_name)').order('created_at',{ascending:false}),activities:supabase.from('activities').select('*,projects(project_name)').order('activity_date',{ascending:false}),contracts:supabase.from('contracts').select('*,projects(project_name)').order('contract_date',{ascending:false}),schedules:supabase.from('collection_schedules').select('*,projects(project_name)').order('due_date'),payments:supabase.from('payments').select('*,projects(project_name)').order('payment_date',{ascending:false}),kpis:supabase.from('kpi_targets').select('*,profiles:employee_id(full_name)').order('created_at',{ascending:false})};
 const entries=Object.entries(queries);const out={...data};for(const [k,q] of entries){const r=await q;if(!r.error)out[k]=r.data||[];else if(k==='profiles'&&isAdmin) setError(r.error.message)}setData(out)}
 function open(kind,initial={}){setForm({...empty[kind],...initial});setModal(kind)}
 function close(){setModal(null);setForm({})}
 function set(k,v){setForm(f=>({...f,[k]:v}))}
 async function save(){setSaving(true);setNotice('');let table='';let payload={...form};const kind=modal;
 if(kind==='employee'){try{const r=await fetch('/api/admin/employees',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload})});const j=await r.json();if(!r.ok)throw new Error(j.error);setNotice('Employee created');close();await load()}catch(e){setError(e.message)}setSaving(false);return}
 const map={company:'companies',contact:'contacts',project:'projects',activity:'activities',contract:'contracts',schedule:'collection_schedules',payment:'payments',kpi:'kpi_targets'};table=map[kind];for(const k of Object.keys(payload))if(payload[k]==='')payload[k]=null;if(['area','expected_value','contract_value','amount','target_value','weight'].some(k=>k in payload))for(const k of ['area','expected_value','contract_value','amount','target_value','weight'])if(payload[k]!==null)payload[k]=Number(payload[k]);
 const {error:e}=await supabase.from(table).insert(payload);if(e)setError(e.message);else{setNotice(`${modules[tab]||'Record'} saved`);close();await load()}setSaving(false)}
 async function logout(){await supabase.auth.signOut();router.replace('/login')}
 const totals={projects:data.projects.length,pipeline:data.projects.filter(x=>!['closed','lost'].includes(x.stage)).reduce((a,x)=>a+Number(x.expected_value||0),0),contract:data.projects.reduce((a,x)=>a+Number(x.contract_value||0),0),collected:data.payments.reduce((a,x)=>a+Number(x.amount||0),0)};
 if(loading)return <div className="loading-screen">EMDAD CRM</div>;
 return <main dir={lang==='ar'?'rtl':'ltr'} className="app"><header className="topbar"><div><div className="brand">EMDAD <span>CRM</span></div><small>{profile?.full_name} · {profile?.role==='admin'?'Administrator':'Sales Employee'}</small></div><div className="top-actions"><button className="lang" onClick={()=>{const n=lang==='en'?'ar':'en';setLang(n);localStorage.setItem('emdad_lang',n)}}>{lang==='en'?'العربية':'English'}</button><button className="btn btn-secondary" onClick={logout}>{t.Logout}</button></div></header><div className="shell"><aside className="sidebar"><nav>{Object.entries(modules).map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{t[v]||v}</button>)}</nav></aside><section className="content"><div className="heading"><div><h1>{t[modules[tab]]||modules[tab]}</h1><p>{lang==='ar'?'إدارة المبيعات والمشاريع والتحصيلات في مكان واحد':'Manage sales, projects, follow-ups and collections in one place.'}</p></div>{tab!=='dashboard'&&tab!=='reports'&&<button className="btn btn-primary" onClick={()=>open(tab==='employees'?'employee':tab==='companies'?'company':tab==='contacts'?'contact':tab==='projects'?'project':tab==='followups'?'activity':tab==='contracts'?'contract':tab==='collections'?'payment':'kpi')}>+ {t.Add}</button>}</div>{error&&<div className="alert">{error}</div>}{notice&&<div className="success">{notice}</div>}{tab==='dashboard'?<Dashboard totals={totals} data={data} t={t}/>:tab==='reports'?<Reports data={data} t={t}/>:<Module tab={tab} data={data} t={t} lang={lang} onAdd={open} onRefresh={load}/>}</section></div>{modal&&<Modal kind={modal} form={form} set={set} data={data} t={t} lang={lang} onClose={close} onSave={save} saving={saving}/>}</main>
}

function Dashboard({totals,data,t}){return <><div className="cards"><Metric label={t.Projects} value={totals.projects}/><Metric label={t.Expected} value={money(totals.pipeline)}/><Metric label={t.Contract} value={money(totals.contract)}/><Metric label={t.Collected} value={money(totals.collected)}/></div><div className="grid2"><div className="panel"><h3>Pipeline</h3>{['lead','pricing','technical','tender','on_hand','negotiation','won','contract','collection','closed','lost'].map(s=><div className="barrow" key={s}><span>{s.replace('_',' ')}</span><b>{data.projects.filter(p=>p.stage===s).length}</b></div>)}</div><div className="panel"><h3>Top Opportunities</h3>{data.projects.slice(0,7).map(p=><div className="listrow" key={p.id}><div><b>{p.project_name}</b><small>{p.companies?.name||''}</small></div><strong>{money(p.expected_value)}</strong></div>)}{!data.projects.length&&<p className="muted">{t.NoData}</p>}</div></div></>}
function Reports({data,t}){const byEmp={};data.projects.forEach(p=>{const n=p.profiles?.full_name||'Unassigned';byEmp[n]=(byEmp[n]||0)+Number(p.contract_value||p.expected_value||0)});return <div className="panel"><h3>Employee Performance</h3><div className="table-wrap"><table className="table"><thead><tr><th>Employee</th><th>Projects</th><th>Pipeline</th><th>Contract</th><th>Collected</th></tr></thead><tbody>{data.profiles.filter(p=>p.role==='employee').map(e=>{const ps=data.projects.filter(p=>p.employee_id===e.id);const col=data.payments.filter(x=>x.employee_id===e.id).reduce((a,x)=>a+Number(x.amount||0),0);return <tr key={e.id}><td>{e.full_name}</td><td>{ps.length}</td><td>{money(ps.reduce((a,x)=>a+Number(x.expected_value||0),0))}</td><td>{money(ps.reduce((a,x)=>a+Number(x.contract_value||0),0))}</td><td>{money(col)}</td></tr>})}</tbody></table></div></div>}
function Module({tab,data,t,onAdd}){const configs={employees:['profiles',['full_name','email','phone','job_title','role','is_active']],companies:['companies',['name','sector','company_type','city','phone','email']],contacts:['contacts',['full_name','company','position','mobile','email']],projects:['projects',['project_name','company','employee','stage','expected_value','contract_value']],pipeline:['projects',['project_name','company','employee','stage','expected_value']],followups:['activities',['project','activity_type','activity_date','subject','next_follow_up_date']],contracts:['contracts',['project','contract_number','contract_date','contract_value']],collections:['payments',['project','payment_date','amount','reference']],kpis:['kpis',['employee','name','target_value','weight']]};const c=configs[tab];const rows=data[c?.[0]]||[];return <div className="panel"><div className="table-wrap"><table className="table"><thead><tr>{(c?.[1]||[]).map(x=><th key={x}>{x.replace('_',' ')}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{(c?.[1]||[]).map(k=><td key={k}>{display(r,k)}</td>)}</tr>)}</tbody></table></div>{!rows.length&&<div className="empty">{t.NoData}</div>}</div>}
function display(r,k){if(k==='company')return r.companies?.name||'—';if(k==='employee')return r.profiles?.full_name||'—';if(k==='project')return r.projects?.project_name||'—';if(k==='is_active')return r[k]?'Active':'Inactive';if(['expected_value','contract_value','amount','target_value'].includes(k))return money(r[k]);return r[k]||'—'}
function Modal({kind,form,set,data,t,onClose,onSave,saving}){const fields={employee:[['full_name','Full name'],['email','Email','email'],['phone','Phone'],['job_title','Job title']],company:[['name','Company name'],['sector','Sector'],['company_type','Company type'],['city','City'],['phone','Phone'],['email','Email','email'],['website','Website'],['notes','Notes']],contact:[['company_id','Company','company'],['full_name','Full name'],['position','Position'],['mobile','Mobile'],['email','Email','email'],['contact_role','Role']],project:[['project_name','Project name'],['company_id','Company','company'],['contact_id','Contact','contact'],['employee_id','Employee','employee'],['sector','Sector'],['project_type','Project type'],['scope','Scope'],['consultant','Consultant'],['key_person','Key person'],['location','Location'],['area','Area','number'],['expected_value','Expected value','number'],['stage','Stage','stage']],activity:[['project_id','Project','project'],['activity_type','Activity type','activity'],['subject','Subject'],['description','Description'],['outcome','Outcome'],['next_follow_up_date','Next follow-up','datetime-local'],['next_action','Next action']],contract:[['project_id','Project','project'],['contract_number','Contract number'],['contract_date','Contract date','date'],['contract_value','Contract value','number'],['notes','Notes']],payment:[['project_id','Project','project'],['collection_schedule_id','Schedule','schedule'],['payment_date','Payment date','date'],['amount','Amount','number'],['reference','Reference'],['notes','Notes']],kpi:[['employee_id','Employee','employee'],['name','KPI name'],['target_value','Target','number'],['weight','Weight %','number'],['period_start','Start','date'],['period_end','End','date']]};return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>{t.Add} {kind}</h2><button onClick={onClose}>×</button></div><div className="form-grid">{fields[kind].map(([k,label,type])=><Field key={k} k={k} label={label} type={type} value={form[k]} set={set} data={data} kind={kind}/>)}<div className="modal-actions"><button className="btn btn-secondary" onClick={onClose}>{t.Cancel}</button><button className="btn btn-primary" onClick={onSave} disabled={saving}>{saving?'Saving…':t.Save}</button></div></div></div></div>}
function Field({k,label,type,value,set,data}){if(['company','contact','employee','project','schedule','activity','stage'].includes(type)){let opts=[],source=type==='company'?data.companies:type==='contact'?data.contacts:type==='employee'?data.profiles.filter(x=>x.role==='employee'):type==='project'?data.projects:type==='schedule'?data.schedules:[];if(type==='stage')opts=stages.map(x=>({id:x,name:x}));else opts=source.map(x=>({id:x.id,name:x.name||x.full_name||x.project_name||x.description}));if(type==='activity')opts=activityTypes.map(x=>({id:x,name:x}));return <div className="field"><label>{label}</label><select value={value||''} onChange={e=>set(k,e.target.value)}><option value="">Select...</option>{opts.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div>};return <div className="field"><label>{label}</label>{type==='textarea'?<textarea value={value||''} onChange={e=>set(k,e.target.value)}/>:<input type={type||'text'} value={value||''} onChange={e=>set(k,e.target.value)}/>}</div>}
function Metric({label,value}){return <div className="card"><span className="card-label">{label}</span><strong className="card-value">{value}</strong></div>}
function money(n){return `EGP ${Number(n||0).toLocaleString('en-US',{maximumFractionDigits:0})}`}
