'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase-browser';

const LABEL={new:'New',pricing_technical:'Pricing & Technical',quotation_ready:'Quotation Ready',quotation_sent:'Quotation Sent',follow_up:'Follow-up',negotiation:'Negotiation',won:'Won',lost:'Lost',on_hold:'On hold',cancelled:'Cancelled'};
const money=v=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Number(v||0));
const fmtDate=v=>v?new Date(v).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'—';

export default function Home(){
 const [tab,setTab]=useState('dashboard'),[data,setData]=useState({companies:[],projects:[],pipeline:[],activities:[],tasks:[],collections:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(''),[modal,setModal]=useState(null),[form,setForm]=useState({});
 async function load(){setBusy(true);setError('');try{const qs=await Promise.all([
  supabase.from('companies').select('*').order('name'),
  supabase.from('projects').select('*,companies(name)').order('created_at',{ascending:false}),
  supabase.from('pipeline').select('*,projects(name,companies(name),temperature)').order('added_at',{ascending:false}),
  supabase.from('activities').select('*,companies(name),projects(name)').order('activity_at',{ascending:false}),
  supabase.from('tasks').select('*,companies(name),projects(name)').order('due_date'),
  supabase.from('collections').select('*,projects(name,companies(name))').order('due_date')
 ]);const bad=qs.find(x=>x.error);if(bad)throw bad.error;setData({companies:qs[0].data||[],projects:qs[1].data||[],pipeline:qs[2].data||[],activities:qs[3].data||[],tasks:qs[4].data||[],collections:qs[5].data||[]})}catch(e){setError(e?.message||'Database connection failed');setData({companies:[],projects:[],pipeline:[],activities:[],tasks:[],collections:[]})}finally{setLoading(false);setBusy(false)}}
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>{const now=new Date(),ws=new Date(now);ws.setHours(0,0,0,0);ws.setDate(ws.getDate()-((ws.getDay()+6)%7));const acts=data.activities.filter(x=>x.status==='completed'&&new Date(x.activity_at)>=ws),p=data.pipeline.filter(x=>x.status==='active');return{newProjects:data.projects.filter(x=>new Date(x.received_at)>=ws).length,pipelineAdded:data.pipeline.filter(x=>new Date(x.added_at)>=ws).length,hot:data.projects.filter(x=>x.temperature==='hot'&&!['won','lost','cancelled'].includes(x.status)).length,calls:acts.filter(x=>x.type==='call').length,customerVisits:acts.filter(x=>x.type==='customer_visit').length,consultantVisits:acts.filter(x=>x.type==='consultant_visit').length,pipelineValue:p.reduce((s,x)=>s+Number(x.value||0),0),weighted:p.reduce((s,x)=>s+Number(x.value||0)*Number(x.probability||0)/100,0),collected:data.collections.reduce((s,x)=>s+Number(x.amount_collected||0),0),remaining:data.collections.reduce((s,x)=>s+Math.max(0,Number(x.amount_due||0)-Number(x.amount_collected||0)),0),overdue:data.tasks.filter(x=>x.status==='pending'&&x.due_date&&new Date(x.due_date+'T23:59:59')<now).length}},[data]);
 const q=search.toLowerCase();const projects=data.projects.filter(x=>`${x.name} ${x.companies?.name||''}`.toLowerCase().includes(q));const companies=data.companies.filter(x=>`${x.name} ${x.city||''}`.toLowerCase().includes(q));
 const nav=[['dashboard','Overview'],['projects','Projects'],['pipeline','Pipeline'],['activities','Activities'],['companies','Companies'],['collections','Collections']];
 const open=kind=>{setForm({});setModal(kind)};
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function save(){setBusy(true);setError('');try{if(modal==='company'){const r=await supabase.from('companies').insert({name:form.name,company_type:form.company_type||'client',city:form.city||null,phone:form.phone||null,email:form.email||null});if(r.error)throw r.error}else if(modal==='project'){const p={name:form.name,company_id:form.company_id,estimated_value:form.estimated_value?Number(form.estimated_value):null,win_probability:Number(form.win_probability||0),temperature:form.temperature||'cold',status:form.status||'new',project_type:form.project_type||null,next_action:form.next_action||null,next_action_date:form.next_action_date||null};const r=await supabase.from('projects').insert(p).select().single();if(r.error)throw r.error;if(p.win_probability>50){const z=await supabase.from('pipeline').insert({project_id:r.data.id,value:p.estimated_value||0,probability:p.win_probability,expected_closing_date:form.expected_closing_date||null});if(z.error)throw z.error}}else{const p={subject:form.subject||form.type||'Activity',type:form.type||'other',status:'completed',company_id:form.company_id||null,project_id:form.project_id||null,activity_at:new Date().toISOString(),result:form.result||null,next_action:form.next_action||null,next_action_date:form.next_action_date||null};const r=await supabase.from('activities').insert(p);if(r.error)throw r.error;if(p.project_id&&p.next_action_date){const z=await supabase.from('tasks').insert({company_id:p.company_id,project_id:p.project_id,title:p.next_action||'Follow-up',due_date:p.next_action_date,priority:'medium',status:'pending'});if(z.error)throw z.error)}}setModal(null);await load()}catch(e){setError(e?.message||'Save failed')}finally{setBusy(false)}}
 if(loading)return <div className="loading">Loading workspace…</div>;
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-mark">S</div><div><div className="brand-name">Sales OS</div><span className="brand-sub">Private workspace</span></div></div><nav className="nav">{nav.map(([id,label])=><button key={id} className={`nav-btn ${tab===id?'active':''}`} onClick={()=>{setTab(id);setSearch('')}}>{label}</button>)}</nav><div className="sidebar-foot"><small>Workspace</small><strong>Personal</strong></div></aside><section className="main"><header className="topbar"><div><div className="crumb">Sales operations</div><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><div className="top-actions">{tab!=='dashboard'&&<input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search"/>}<button className="btn" onClick={load}>{busy?'Refreshing…':'Refresh'}</button>{['projects','activities','companies'].includes(tab)&&<button className="btn primary" onClick={()=>open(tab==='projects'?'project':tab==='activities'?'activity':'company')}>+ Add</button>}</div></header><main className="content">{error&&<div className="alert">{error}. The interface is available, but live data could not be loaded.</div>}{tab==='dashboard'?<Dashboard stats={stats} data={data} go={setTab} open={open}/>:tab==='projects'?<Projects items={projects} open={open}/>:tab==='pipeline'?<Pipeline items={data.pipeline}/>:tab==='activities'?<Activities items={data.activities}/>:tab==='companies'?<Companies items={companies} open={open}/>:<Collections data={data}/>}</main></section>{modal&&<Modal kind={modal} form={form} set={set} data={data} close={()=>setModal(null)} save={save} busy={busy}/>}</div>}

function Dashboard({stats,data,go,open}){const due=data.tasks.filter(x=>x.status==='pending'&&x.due_date&&new Date(x.due_date+'T23:59:59')<=new Date()).slice(0,5),hot=data.projects.filter(x=>x.temperature==='hot'&&!['won','lost','cancelled'].includes(x.status)).slice(0,5);return <><section className="hero"><div><div className="eyebrow">Today’s control room</div><h2>Know what needs your attention.</h2><p>Track opportunities, actions and cash without the noise.</p></div><div className="hero-actions"><button className="btn" onClick={()=>open('activity')}>Log activity</button><button className="btn primary" onClick={()=>open('project')}>New project</button></div></section><section className="kpis">{[['New projects',stats.newProjects,'this week'],['Pipeline added',stats.pipelineAdded,'this week'],['Hot projects',stats.hot,'active'],['Calls',stats.calls,'this week'],['Customer visits',stats.customerVisits,'this week'],['Consultant visits',stats.consultantVisits,'this week']].map(x=><div className="kpi" key={x[0]}><div className="kpi-label">{x[0]}</div><div className="kpi-value">{x[1]}</div><div className="kpi-meta">{x[2]}</div></div>)}</section><section className="dashboard-grid"><div className="card"><div className="card-head"><h3>Needs attention</h3><button className="link" onClick={()=>go('activities')}>View activities →</button></div>{due.length?<div className="list">{due.map(x=><div className="list-row" key={x.id}><div className="list-main"><b>{x.title}</b><span>{x.projects?.name||x.companies?.name||'General'}</span></div><strong className="list-value">{fmtDate(x.due_date)}</strong></div>)}</div>:<div className="empty">No overdue follow-ups</div>}</div><div className="card"><div className="card-head"><h3>Hot opportunities</h3><button className="link" onClick={()=>go('pipeline')}>Open pipeline →</button></div>{hot.length?<div className="list">{hot.map(x=><div className="list-row" key={x.id}><div className="list-main"><b>{x.name}</b><span>{x.companies?.name||'—'} · {LABEL[x.status]||x.status}</span></div><strong className="list-value">{money(x.estimated_value)} EGP</strong></div>)}</div>:<div className="empty">No hot projects yet</div>}</div></section><section className="finance">{[['Active pipeline',money(stats.pipelineValue)+' EGP','Weighted '+money(stats.weighted)+' EGP'],['Collected',money(stats.collected)+' EGP','Recorded collections'],['Remaining',money(stats.remaining)+' EGP','Open receivables']].map(x=><div className="metric" key={x[0]}><div className="metric-label">{x[0]}</div><div className="metric-value">{x[1]}</div><div className="metric-meta">{x[2]}</div></div>)}</section></>}
function Projects({items,open}){return <section className="card page-card"><div className="page-title"><h2>Projects</h2><button className="btn primary" onClick={()=>open('project')}>+ New project</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Project</th><th>Company</th><th>Stage</th><th>Temperature</th><th>Value</th><th>Next action</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td><b>{x.name}</b><span className="sub">{x.project_type||'HVAC project'}</span></td><td>{x.companies?.name||'—'}</td><td>{LABEL[x.status]||x.status}</td><td><span className={`pill ${x.temperature}`}>{x.temperature}</span></td><td>{money(x.estimated_value)} EGP</td><td>{x.next_action||'—'}<span className="sub">{fmtDate(x.next_action_date)}</span></td></tr>):<tr><td colSpan="6" className="empty">No projects yet</td></tr>}</tbody></table></div></section>}
function Pipeline({items}){return <div className="kanban">{['active','won','lost','on_hold'].map(c=><section className="column" key={c}><div className="column-head"><strong>{c.replace('_',' ').toUpperCase()}</strong><span className="count">{items.filter(x=>x.status===c).length}</span></div>{items.filter(x=>x.status===c).map(x=><div className="deal" key={x.id}><span className={`pill ${x.projects?.temperature||'cold'}`}>{x.projects?.temperature||'cold'}</span><b>{x.projects?.name||'Project'}</b><small>{x.projects?.companies?.name||'—'}</small><strong>{money(x.value)} EGP</strong><small>{Number(x.probability||0)}% probability</small></div>)}</section>)}</div>}
function Activities({items}){return <section className="card page-card"><div className="page-title"><h2>Activities & follow-ups</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Activity</th><th>Company</th><th>Project</th><th>Type</th><th>Next follow-up</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td><b>{x.subject||x.type}</b><span className="sub">{fmtDate(x.activity_at)}</span></td><td>{x.companies?.name||'—'}</td><td>{x.projects?.name||'—'}</td><td>{x.type}</td><td>{fmtDate(x.next_action_date)}</td></tr>):<tr><td colSpan="5" className="empty">No activities yet</td></tr>}</tbody></table></div></section>}
function Companies({items,open}){return <section className="card page-card"><div className="page-title"><h2>Companies</h2><button className="btn primary" onClick={()=>open('company')}>+ New company</button></div><div className="company-grid">{items.length?items.map(x=><div className="company" key={x.id}><div className="company-avatar">{x.name?.[0]||'C'}</div><div><b>{x.name}</b><small>{x.company_type} · {x.city||'—'}</small><span>{x.phone||x.email||'No contact details'}</span></div></div>):<div className="empty">No companies yet</div>}</div></section>}
function Collections({data}){const due=data.collections.reduce((s,x)=>s+Number(x.amount_due||0),0),paid=data.collections.reduce((s,x)=>s+Number(x.amount_collected||0),0);return <><section className="finance"><div className="metric"><div className="metric-label">Amount due</div><div className="metric-value">{money(due)} EGP</div></div><div className="metric"><div className="metric-label">Collected</div><div className="metric-value">{money(paid)} EGP</div></div><div className="metric"><div className="metric-label">Remaining</div><div className="metric-value">{money(Math.max(0,due-paid))} EGP</div></div></section><section className="card page-card collection-card"><div className="page-title"><h2>Collections</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Project</th><th>Contract</th><th>Due</th><th>Collected</th><th>Status</th></tr></thead><tbody>{data.collections.length?data.collections.map(x=><tr key={x.id}><td>{x.projects?.name||'—'}</td><td>{money(x.contract_value)} EGP</td><td>{money(x.amount_due)} EGP</td><td>{money(x.amount_collected)} EGP</td><td>{x.status}</td></tr>):<tr><td colSpan="5" className="empty">No collection records yet</td></tr>}</tbody></table></div></section></>}
function Modal({kind,form,set,data,close,save,busy}){const field=(label,k,type='text',full=false)=><label className={full?'field full':'field'}><span>{label}</span><input type={type} value={form[k]||''} onChange={e=>set(k,e.target.value)}/></label>;const select=(label,k,opts,full=false)=><label className={full?'field full':'field'}><span>{label}</span><select value={form[k]||''} onChange={e=>set(k,e.target.value)}><option value="">Select…</option>{opts.map(o=>typeof o==='string'?<option key={o} value={o}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;return <div className="overlay"><div className="modal"><div className="modal-head"><div><span className="eyebrow">{kind==='project'?'NEW OPPORTUNITY':kind==='activity'?'ACTIVITY':'CUSTOMER'}</span><h3>{kind==='project'?'New project':kind==='activity'?'Log activity':'New company'}</h3></div><button className="close" onClick={close}>×</button></div><div className="form">{kind==='company'?<>{field('Company name','name','text',true)}{select('Company type','company_type',['client','consultant','contractor','developer','supplier','other'])}{field('City','city')}{field('Phone','phone')}{field('Email','email')}</>:kind==='project'?<>{field('Project name','name','text',true)}{select('Company','company_id',data.companies.map(x=>({value:x.id,label:x.name})),true)}{field('Estimated value','estimated_value','number')}{field('Win probability %','win_probability','number')}{select('Temperature','temperature',['cold','warm','hot'])}{select('Stage','status',Object.entries(LABEL).map(([value,label])=>({value,label})))}{field('Project type','project_type')}{field('Next action','next_action','text',true)}{field('Next action date','next_action_date','date')}</>:<>{select('Activity type','type',['call','customer_visit','consultant_visit','meeting','site_visit','email','follow_up','other'])}{select('Project','project_id',data.projects.map(x=>({value:x.id,label:x.name})),true)}{field('Subject','subject','text',true)}{field('Result / notes','result','text',true)}{field('Next action','next_action')}{field('Next action date','next_action_date','date')}</>}</div><div className="modal-foot"><button className="btn" onClick={close}>Cancel</button><button className="btn primary" onClick={save} disabled={busy}>{busy?'Saving…':'Save'}</button></div></div></div>}
