'use client';
import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase-browser';
const sourceLabel={email:'Email',whatsapp:'WhatsApp',manual:'Manual',other:'Other'};
export default function SalesInbox(){
 const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');const {data,error}=await supabase.from('sales_inbox').select('id,source,sender_name,sender_address,subject,body,received_at,status,ai_summary,ai_extracted_data,suggested_company_id,suggested_project_id,suggested_contact_id,suggested_action,review_notes').order('received_at',{ascending:false}).limit(100);if(error)setError(error.message);else setItems(data||[]);setLoading(false)},[]);
 useEffect(()=>{load()},[load]);
 async function approve(){if(!selected)return;setBusy(true);setError('');const {error}=await supabase.rpc('approve_sales_inbox_item',{p_inbox_id:selected.id,p_company_id:selected.suggested_company_id||null,p_contact_id:selected.suggested_contact_id||null,p_project_id:selected.suggested_project_id||null,p_review_notes:selected.review_notes||null});if(error)setError(error.message);else{setItems(x=>x.map(i=>i.id===selected.id?{...i,status:'approved'}:i));setSelected(x=>x?{...x,status:'approved'}:x)}setBusy(false)}
 async function reject(){if(!selected)return;setBusy(true);setError('');const {error}=await supabase.from('sales_inbox').update({status:'rejected',reviewed_at:new Date().toISOString()}).eq('id',selected.id);if(error)setError(error.message);else{setItems(x=>x.map(i=>i.id===selected.id?{...i,status:'rejected'}:i));setSelected(x=>x?{...x,status:'rejected'}:x)}setBusy(false)}
 const extracted=selected?.ai_extracted_data||{};
 return <section className="inbox-layout"><div className="panel inbox-list"><div className="panel-head"><div><b>Sales Inbox</b><small>Incoming email and WhatsApp leads</small></div><button onClick={load} disabled={loading}>↻ Refresh</button></div>{loading?<div className="empty">Loading inbox…</div>:items.length===0?<div className="empty">No incoming messages yet.</div>:items.map(x=><button className={`inbox-item ${selected?.id===x.id?'selected':''}`} key={x.id} onClick={()=>setSelected(x)}><div className="inbox-source">{sourceLabel[x.source]||x.source}</div><div className="inbox-main"><b>{x.subject||'No subject'}</b><span>{x.sender_name||x.sender_address||'Unknown sender'}</span><small>{x.ai_summary||x.body?.slice(0,90)||'No preview'}</small></div><div className="inbox-meta"><span className={`status-dot ${x.status}`}/>{new Date(x.received_at).toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}</div></button>)}</div><div className="panel inbox-detail">{error&&<div className="alert">{error}</div>}{!selected?<div className="empty detail-empty"><b>Select a message</b><span>Review incoming leads before they enter the CRM.</span></div>:<><div className="detail-head"><div><span className="eyebrow">{sourceLabel[selected.source]||selected.source}</span><h2>{selected.subject||'No subject'}</h2><p>{selected.sender_name||'Unknown'} · {selected.sender_address||'No address'}</p></div><span className={`status-pill ${selected.status}`}>{selected.status}</span></div><div className="message-body">{selected.body||'No message body.'}</div><div className="extraction"><div className="panel-head"><b>AI / CRM suggestion</b><small>Review before creating or updating CRM records</small></div><div className="extract-grid"><div><span>Company</span><b>{extracted.company_name||selected.suggested_company_id||'Needs matching'}</b></div><div><span>Contact</span><b>{extracted.contact_name||selected.suggested_contact_id||'Needs matching'}</b></div><div><span>Project</span><b>{extracted.project_name||selected.suggested_project_id||'New / needs matching'}</b></div><div><span>Project type</span><b>{extracted.project_type||'—'}</b></div><div><span>Estimated value</span><b>{extracted.estimated_value||'—'}</b></div><div><span>Action</span><b>{selected.suggested_action||'Review message'}</b></div></div>{selected.ai_summary&&<p className="summary">{selected.ai_summary}</p>}</div><div className="detail-actions"><button className="outline" disabled={busy||selected.status!=='new'} onClick={reject}>Reject</button><button className="primary" disabled={busy||selected.status!=='new'} onClick={approve}>{busy?'Saving…':'Approve & Continue'}</button></div></>}</div></section>
}
