'use client';
import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase-browser';

const LABEL={new:'New',pricing_technical:'Pricing & Technical',quotation_ready:'Quotation Ready',quotation_sent:'Quotation Sent',follow_up:'Follow-up',negotiation:'Negotiation',won:'Won',lost:'Lost',on_hold:'On hold',cancelled:'Cancelled'};
const TYPES=['call','customer_visit','consultant_visit','meeting','site_visit','email','follow_up','pricing_follow_up','technical_follow_up','collection_follow_up','other'];
const money=v=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Number(v||0));
const date=v=>v?new Date(v).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'—';

export default function SalesApp(){
 const [tab,setTab]=useState('dashboard'),[data,setData]=useState({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(''),[modal,setModal]=useState(null),[form,setForm]=useState({});
 const load=useCallback(async(next=tab)=>{setBusy(true);setError('');try{
  let result={};
  if(next==='dashboard'){
   const [summary,hot,tasks]=await Promise.all([
    supabase.rpc('dashboard_summary'),
    supabase.from('projects').select('id,name,estimated_value,status,temperature,companies(name)').eq('temperature','hot').not('status','in','(won,lost,cancelled)').order('estimated_value',{ascending:false}).limit(6),
    supabase.from('tasks').select('id,title,due_date,projects(name),companies(name)').eq('status','pending').lt('due_date',new Date().toISOString().slice(0,10)).order('due_date').limit(6)
   ]); if(summary.error)throw summary.error;if(hot.error)throw hot.error;if(tasks.error)throw tasks.error;result={summary:summary.data||{},hot:hot.data||[],tasks:tasks.data||[]};
  } else if(next==='projects'){
   const [p,c]=await Promise.all([supabase.from('projects').select('id,name,project_type,estimated_value,win_probability,temperature,status,next_action,next_action_date,companies(name)').order('created_at',{ascending:false}).limit(200),supabase.from('companies').select('id,name').order('name').limit(500)]);if(p.error)throw p.error;if(c.error)throw c.error;result={projects:p.data||[],companies:c.data||[]};
  } else if(next==='pipeline'){
   const p=await supabase.from('pipeline').select('id,value,probability,status,projects(id,name,temperature,companies(name))').order('added_at',{ascending:false}).limit(300);if(p.error)throw p.error;result={pipeline:p.data||[]};
  } else if(next==='activities'){
   const [a,c,p]=await Promise.all([supabase.from('activities').select('id,subject,type,status,activity_at,result,next_action,next_action_date,companies(name),projects(name)').order('activity_at',{ascending:false}).limit(200),supabase.from('companies').select('id,name').order('name').limit(500),supabase.from('projects').select('id,name').order('name').limit(500)]);if(a.error)throw a.error;if(c.error)throw c.error;if(p.error)throw p.error;result={activities:a.data||[],companies:c.data||[],projects:p.data||[]};
  } else if(next==='companies'){
   const c=await supabase.from('companies').select('id,name,company_type,city,phone,email').order('name').limit(500);if(c.error)throw c.error;result={companies:c.data||[]};
  } else if(next==='collections'){
   const c=await supabase.from('collections').select('id,contract_value,amount_due,amount_collected,status,due_date,projects(name,companies(name))').order('due_date').limit(300);if(c.error)throw c.error;result={collections:c.data||[]};
  }
  setData(d=>({...d,...result}));
 }catch(e){setError(e?.message||'Could not load data')}finally{setLoading(false);setBusy(false)}},[tab]);
 useEffect(()=>{load('dashboard')},[load]);
 useEffect(()=>{if(tab!=='dashboard')load(tab)},[tab,load]);
 const go=id=>{setSearch('');setTab(id)};
 const open=kind=>{setForm({});setModal(kind)};const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function save(){setBusy(true);setError('');try{
  if(modal==='company'){const r=await supabase.from('companies').insert({name:form.name,company_type:form.company_type||'client',city:form.city||null,phone:form.phone||null,email:form.email||null});if(r.error)throw r.error}
  if(modal==='project'){const p={name:form.name,company_id:form.company_id||null,estimated_value:form.estimated_value?Number(form.estimated_value):null,win_probability:Number(form.win_probability||0),temperature:form.temperature||'cold',status:form.status||'new',project_type:form.project_type||null,next_action:form.next_action||null,next_action_date:form.next_action_date||null};const r=await supabase.from('projects').insert(p).select('id').single();if(r.error)throw r.error;if(p.win_probability>50){const z=await supabase.from('pipeline').insert({project_id:r.data.id,value:p.estimated_value||0,probability:p.win_probability});if(z.error)throw z.error}}
  if(modal==='activity'){const a={subject:form.subject||form.type||'Activity',type:form.type||'other',status:'completed',company_id:form.company_id||null,project_id:form.project_id||null,activity_at:new Date().toISOString(),result:form.result||null,next_action:form.next_action||null,next_action_date:form.next_action_date||null};const r=await supabase.from('activities').insert(a);if(r.error)throw r.error;if(a.project_id&&a.next_action_date){const z=await supabase.from('tasks').insert({company_id:a.company_id,project_id:a.project_id,title:a.next_action||'Follow-up',due_date:a.next_action_date,priority:'medium',status:'pending'});if(z.error)throw z.error}}
  setModal(null);await load(tab);
 }catch(e){setError(e?.message||'Save failed')}finally{setBusy(false)}}
 const nav=[['dashboard','Overview'],['projects','Projects'],['pipeline','Pipeline'],['activities','Activities'],['companies','Companies'],['collections','Collections']];
 if(loading)return <div className="loading">Loading workspace…</div>;
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-mark">S</div><div><div className="brand-name">Sales OS</div><span className="brand-sub">Private workspace</span></div></div><nav className="nav">{nav.map(([id,label])=><button key={id} className={`nav-btn ${tab===id?'active':''}`} onClick={()=>go(id)}>{label}</button>)}</nav><div className="sidebar-foot"><small>Workspace</small><strong>Personal</strong></div></aside><section className="main"><header className="topbar"><div><div className="crumb">Sales operations</div><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><div className="top-actions">{tab!=='dashboard'&&<input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search"/>}<button className="btn" onClick={()=>load(tab)}>{busy?'Refreshing…':'Refresh'}</button>{['projects','activities','companies'].includes(tab)&&<button className="btn primary" onClick={()=>open(tab==='projects'?'project':tab==='activities'?'activity':'company')}>+ Add</button>}</div></header><main className="content">{error&&<div className="alert">{error}</div>}{tab==='dashboard'?<Dashboard data={data} go={go} open={open}/>:tab==='projects'?<Projects data={data} search={search}/>:tab==='pipeline'?<Pipeline items={data.pipeline||[]}/>:tab==='activities'?<Activities data={data} search={search}/>:tab==='companies'?<Companies items={(data.companies||[]).filter(x=>`${x.name} ${x.city||''}`.toLowerCase().includes(search.toLowerCase()))}/>:<Collections items={data.collections||[]}/>}</main></section>{modal&&<Modal kind={modal} form={form} set={set} data={data} close={()=>setModal(null)} save={save} busy={busy}/>}</div>
}
function Dashboard({data,go,open}){const s=data.summary||{};return <><section className="hero"><div><div className="eyebrow">Today’s control room</div><h2>Know what needs your attention.</h2><p>Track opportunities, actions and cash without the noise.</p></div><div className="hero-actions"><button className="btn" onClick={()=>open('activity')}>Log activity</button><button className="btn primary" onClick={()=>open('project')}>New project</button></div></section><section className="kpis">{[['New projects',s.newProjects],['Pipeline added',s.pipelineAdded],['Hot projects',s.hot],['Calls',s.calls],['Customer visits',s.customerVisits],['Consultant visits',s.consultantVisits]].map(x=><div className="kpi" key={x[0]}><div className="kpi-label">{x[0]}</div><div className="kpi-value">{x[1]??0}</div><div className="kpi-meta">this week</div></div>)}</section><section className="dashboard-grid"><div className="card"><div className="card-head"><h3>Needs attention</h3><button className="link" onClick={()=>go('activities')}>View activities →</button></div>{(data.tasks||[]).length?<div className="list">{data.tasks.map(x=><div className="list-row" key={x.id}><div className="list-main"><b>{x.title}</b><span>{x.projects?.name||x.companies?.name||'General'}</span></div><strong className="list-value">{date(x.due_date)}</strong></div>)}</div>:<div className="empty">No overdue follow-ups</div>}</div><div className="card"><div className="card-head"><h3>Hot opportunities</h3><button className="link" onClick={()=>go('pipeline')}>Open pipeline →</button></div>{(data.hot||[]).length?<div className="list">{data.hot.map(x=><div className="list-row" key={x.id}><div className="list-main"><b>{x.name}</b><span>{x.companies?.name||'—'} · {LABEL[x.status]||x.status}</span></div><strong className="list-value">{money(x.estimated_value)} EGP</strong></div>)}</div>:<div className="empty">No hot projects yet</div>}</div></section><section className="finance">{[['Active pipeline',money(s.pipelineValue)+' EGP','Weighted '+money(s.weighted)+' EGP'],['Collected',money(s.collected)+' EGP','Recorded collections'],['Remaining',money(s.remaining)+' EGP','Open receivables']].map(x=><div className="metric" key={x[0]}><div className="metric-label">{x[0]}</div><div className="metric-value">{x[1]}</div><div className="metric-meta">{x[2]}</div></div>)}</section></>}
function Projects({data,search}){const q=search.toLowerCase();const items=(data.projects||[]).filter(x=>`${x.name} ${x.companies?.name||''}`.toLowerCase().includes(q));return <section className="card page-card"><div className="page-title"><h2>Projects</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Project</th><th>Company</th><th>Stage</th><th>Temperature</th><th>Value</th><th>Next action</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td><b>{x.name}</b><span className="sub">{x.project_type||'HVAC project'}</span></td><td>{x.companies?.name||'—'}</td><td>{LABEL[x.status]||x.status}</td><td><span className={`pill ${x.temperature}`}>{x.temperature}</span></td><td>{money(x.estimated_value)} EGP</td><td>{x.next_action||'—'}<span className="sub">{date(x.next_action_date)}</span></td></tr>):<tr><td colSpan="6" className="empty">No projects yet</td></tr>}</tbody></table></div></section>}
function Pipeline({items}){return <div className="kanban">{['active','won','lost','on_hold'].map(c=><section className="column" key={c}><div className="column-head"><strong>{c.replace('_',' ').toUpperCase()}</strong><span className="count">{items.filter(x=>x.status===c).length}</span></div>{items.filter(x=>x.status===c).map(x=><div className="deal" key={x.id}><span className={`pill ${x.projects?.temperature||'cold'}`}>{x.projects?.temperature||'cold'}</span><b>{x.projects?.name||'Project'}</b><small>{x.projects?.companies?.name||'—'}</small><strong>{money(x.value)} EGP</strong><small>{Number(x.probability||0)}% probability</small></div>)}</section>)}</div>}
function Activities({data,search}){const q=search.toLowerCase();const items=(data.activities||[]).filter(x=>`${x.subject||''} ${x.companies?.name||''} ${x.projects?.name||''}`.toLowerCase().includes(q));return <section className="card page-card"><div className="page-title"><h2>Activities & follow-ups</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Activity</th><th>Company</th><th>Project</th><th>Type</th><th>Next follow-up</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td><b>{x.subject||x.type}</b><span className="sub">{date(x.activity_at)}</span></td><td>{x.companies?.name||'—'}</td><td>{x.projects?.name||'—'}</td><td>{x.type}</td><td>{date(x.next_action_date)}</td></tr>):<tr><td colSpan="5" className="empty">No activities yet</td></tr>}</tbody></table></div></section>}
function Companies({items}){return <section className="card page-card"><div className="page-title"><h2>Companies</h2></div><div className="company-grid">{items.length?items.map(x=><div className="company" key={x.id}><div className="company-avatar">{x.name?.[0]||'C'}</div><div><b>{x.name}</b><small>{x.company_type} · {x.city||'—'}</small><span>{x.phone||x.email||'No contact details'}</span></div></div>):<div className="empty">No companies yet</div>}</div></section>}
function Collections({items}){const due=items.reduce((s,x)=>s+Number(x.amount_due||0),0),paid=items.reduce((s,x)=>s+Number(x.amount_collected||0),0);return <><section className="finance"><div className="metric"><div className="metric-label">Amount due</div><div className="metric-value">{money(due)} EGP</div></div><div className="metric"><div className="metric-label">Collected</div><div className="metric-value">{money(paid)} EGP</div></div><div className="metric"><div className="metric-label">Remaining</div><div className="metric-value">{money(Math.max(0,due-paid))} EGP</div></div></section><section className="card page-card"><div className="page-title"><h2>Collections</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Project</th><th>Contract</th><th>Due</th><th>Collected</th><th>Status</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td>{x.projects?.name||'—'}</td><td>{money(x.contract_value)} EGP</td><td>{money(x.amount_due)} EGP</td><td>{money(x.amount_collected)} EGP</td><td>{x.status}</td></tr>):<tr><td colSpan="5" className="empty">No collection records yet</td></tr>}</tbody></table></div></section></>}
function Modal({kind,form,set,data,close,save,busy}){const field=(label,k,type='text')=><label className="field"><span>{label}</span><input type={type} value={form[k]||''} onChange={e=>set(k,e.target.value)}/></label>;const select=(label,k,opts)=><label className="field"><span>{label}</span><select value={form[k]||''} onChange={e=>set(k,e.target.value)}><option value="">Select…</option>{opts.map(o=>typeof o==='string'?<option key={o} value={o}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;return <div className="overlay"><div className="modal"><div className="modal-head"><div><div className="eyebrow">{kind==='project'?'NEW OPPORTUNITY':kind==='activity'?'ACTIVITY':'CUSTOMER'}</div><h3>{kind==='project'?'New project':kind==='activity'?'Log activity':'New company'}</h3></div><button className="close" onClick={close}>×</button></div><div className="form">{kind==='company'&&<>{field('Company name','name')}{select('Type','company_type',['client','consultant','contractor','developer','supplier','other'])}{field('City','city')}{field('Phone','phone')}{field('Email','email')}</>}{kind==='project'&&<>{field('Project name','name')}{select('Company','company_id',(data.companies||[]).map(x=>({value:x.id,label:x.name})))}{field('Estimated value','estimated_value','number')}{field('Win probability %','win_probability','number')}{select('Temperature','temperature',['cold','warm','hot'])}{select('Stage','status',Object.entries(LABEL).map(([value,label])=>({value,label})))}{field('Project type','project_type')}{field('Next action','next_action')}{field('Next action date','next_action_date','date')}</>}{kind==='activity'&&<>{field('Subject','subject')}{select('Type','type',TYPES)}{select('Company','company_id',(data.companies||[]).map(x=>({value:x.id,label:x.name})))}{select('Project','project_id',(data.projects||[]).map(x=>({value:x.id,label:x.name})))}{field('Result','result')}{field('Next action','next_action')}{field('Next action date','next_action_date','date')}</>}</div><div className="modal-foot"><button className="btn" onClick={close}>Cancel</button><button className="btn primary" onClick={save} disabled={busy}>{busy?'Saving…':'Save'}</button></div></div></div>}
