'use client';

import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import LogoutButton from '@/components/LogoutButton';

const money = v => new Intl.NumberFormat('en-EG',{style:'currency',currency:'EGP',maximumFractionDigits:0}).format(Number(v||0));
const dateText = v => v ? new Date(v).toLocaleDateString('en-GB') : '—';
const today = () => new Date().toISOString().slice(0,10);
const stageFallback = [{id:1,code:'lead',label:'Lead'},{id:2,code:'proposal_technical',label:'Proposal / Technical'},{id:3,code:'following',label:'Follow-up'},{id:4,code:'negotiation',label:'Negotiation'},{id:5,code:'closed_won',label:'Won / Contract'},{id:6,code:'lost',label:'Lost'}];

function Stat({label,value,sub}){return <div className="stat"><div className="stat-label">{label}</div><div className="stat-value">{value}</div>{sub&&<div className="stat-sub">{sub}</div>}</div>}
function Badge({children,tone='neutral'}){return <span className={`badge badge-${tone}`}>{children}</span>}
function Empty({text='No records found'}){return <div className="empty">{text}</div>}

export default function CrmShell({profile}){
  const supabase=createClient();
  const isAdmin=profile?.role==='admin';
  const [tab,setTab]=useState('dashboard'); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [companies,setCompanies]=useState([]); const [contacts,setContacts]=useState([]); const [projects,setProjects]=useState([]); const [employees,setEmployees]=useState([]);
  const [followUps,setFollowUps]=useState([]); const [payments,setPayments]=useState([]); const [contracts,setContracts]=useState([]); const [stages,setStages]=useState(stageFallback);
  const [query,setQuery]=useState(''); const [modal,setModal]=useState(null);

  async function loadAll(){
    setLoading(true); setError('');
    try{
      const results=await Promise.all([
        supabase.from('companies').select('*').order('name'),
        supabase.from('contacts').select('*').order('full_name'),
        supabase.from('projects').select('*').order('updated_at',{ascending:false}),
        supabase.from('profiles').select('*').order('full_name'),
        supabase.from('follow_ups').select('*').order('follow_up_date',{ascending:true}),
        supabase.from('payments').select('*').order('payment_date',{ascending:false}),
        supabase.from('contracts').select('*').order('contract_date',{ascending:false}),
        supabase.from('pipeline_stages').select('*').order('sort_order')
      ]);
      const first=results.find(r=>r.error); if(first) throw first.error;
      const [c,ct,p,e,f,pa,co,st]=results;
      const cm=new Map((c.data||[]).map(x=>[x.id,x])); const em=new Map((e.data||[]).map(x=>[x.id,x])); const pm=new Map((p.data||[]).map(x=>[x.id,x]));
      const stageMap=new Map((st.data||[]).map(x=>[x.id,x]));
      setCompanies((c.data||[]).map(x=>({...x,company_name:x.name}))); 
      setContacts((ct.data||[]).map(x=>({...x,contact_name:x.full_name,companies:cm.get(x.company_id)||null}))); 
      setProjects((p.data||[]).map(x=>{const s=stageMap.get(x.stage_id); return {...x,project_name:x.name,companies:cm.get(x.company_id)||null,profiles:em.get(x.assigned_employee_id)||null,sales_stage:s?.code||'lead',stage_label:s?.name_ar||stageFallback.find(y=>y.id===x.stage_id)?.label||'Lead',actual_contract_value:Number(x.contract_value||0),weighted_value:Number(x.expected_value||0)};}));
      setEmployees((e.data||[]).filter(x=>x.role==='employee'));
      setFollowUps((f.data||[]).map(x=>({...x,projects:pm.get(x.project_id)||null,profiles:em.get(x.employee_id)||null,follow_up_date:x.follow_up_date}))); 
      setPayments(pa.data||[]); setContracts(co.data||[]); setStages(st.data?.length?st.data:stageFallback);
    }catch(err){setError(err.message||'Unable to load CRM data');}
    finally{setLoading(false)}
  }
  useEffect(()=>{loadAll()},[]);

  const filteredProjects=useMemo(()=>projects.filter(p=>{const q=query.toLowerCase().trim(); return !q||[p.project_name,p.companies?.company_name,p.profiles?.full_name].some(v=>String(v||'').toLowerCase().includes(q));}),[projects,query]);
  const active=projects.filter(p=>!['closed_won','lost'].includes(p.sales_stage));
  const contractValue=projects.reduce((s,p)=>s+Number(p.contract_value||0),0);
  const expected=active.reduce((s,p)=>s+Number(p.expected_value||0),0);
  const collected=payments.reduce((s,p)=>s+Number(p.amount||0),0);
  const overdue=followUps.filter(f=>f.follow_up_date&&f.follow_up_date.slice(0,10)<today());
  const dueToday=followUps.filter(f=>f.follow_up_date&&f.follow_up_date.slice(0,10)===today());

  async function save(table,payload,id){setError(''); const r=id?await supabase.from(table).update(payload).eq('id',id):await supabase.from(table).insert(payload); if(r.error){setError(r.error.message);return false} await loadAll();setModal(null);return true}
  async function createEmployee(payload){setError('');try{const r=await fetch('/api/admin/employees',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok){setError(j.error||'Unable to create employee');return false}await loadAll();setModal(null);return true}catch(e){setError(e.message);return false}}

  const nav=[['dashboard','Dashboard'],['projects','Projects'],['companies','Companies'],['contacts','Contacts'],['followups','Follow-ups'],['collections','Collections'],...(isAdmin?[['employees','Employees'],['reports','Reports']]:[])];
  return <div className="crm-app" dir="ltr">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">E</div><div><strong>EMDAD</strong><span>HVAC CRM</span></div></div><div className="user-card"><div className="avatar">{(profile?.full_name||'U').slice(0,1)}</div><div><b>{profile?.full_name||'User'}</b><small>{isAdmin?'Administrator':'Sales Employee'}</small></div></div><nav>{nav.map(([k,l])=><button key={k} className={tab===k?'nav-active':''} onClick={()=>setTab(k)}><span className="nav-dot"/><span className="nav-label">{l}</span></button>)}</nav><div className="sidebar-bottom"><button className="refresh" onClick={loadAll}>↻ Refresh data</button><LogoutButton/></div></aside>
    <main className="main"><header className="topbar"><div><div className="eyebrow">EMDAD ENGINEERING SOLUTIONS</div><h1>{nav.find(x=>x[0]===tab)?.[1]||'Dashboard'}</h1></div><div className="top-actions"><div className="global-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search company, project, contact..."/></div><div className="alert-pill" onClick={()=>setTab('followups')}>! {overdue.length}</div></div></header>{error&&<div className="error-banner">{error}<button onClick={()=>setError('')}>×</button></div>}{loading?<div className="loading"><div className="spinner"/>Loading CRM data...</div>:<>
      {tab==='dashboard'&&<Dashboard isAdmin={isAdmin} projects={projects} employees={employees} expected={expected} contractValue={contractValue} collected={collected} overdue={overdue} dueToday={dueToday} onTab={setTab}/>} 
      {tab==='projects'&&<Projects projects={filteredProjects} employees={employees} isAdmin={isAdmin} stages={stages} onNew={()=>setModal('project')} onEdit={p=>setModal({type:'project',data:p})}/>} 
      {tab==='companies'&&<Companies companies={companies} contacts={contacts} isAdmin={isAdmin} onNew={()=>setModal('company')} onEdit={c=>setModal({type:'company',data:c})}/>} 
      {tab==='contacts'&&<Contacts contacts={contacts} companies={companies} onNew={()=>setModal('contact')} onEdit={c=>setModal({type:'contact',data:c})}/>} 
      {tab==='followups'&&<Followups followUps={followUps} projects={projects} employees={employees} isAdmin={isAdmin} onNew={()=>setModal('followup')} onEdit={x=>setModal({type:'followup',data:x})}/>} 
      {tab==='collections'&&<Collections payments={payments} projects={projects} contracts={contracts} employees={employees} profile={profile} onNew={()=>setModal('payment')}/>} 
      {tab==='employees'&&isAdmin&&<Employees employees={employees} projects={projects} followUps={followUps} payments={payments} onNew={()=>setModal('employee-new')} onEdit={e=>setModal({type:'employee',data:e})}/>} 
      {tab==='reports'&&isAdmin&&<Reports employees={employees} projects={projects} payments={payments} followUps={followUps}/>} 
    </>}</main>
    {modal&&<Modal title={modal==='company'?'New Company':modal==='contact'?'New Contact':modal==='project'?'New Project':modal==='followup'?'New Follow-up':modal==='payment'?'New Collection Payment':modal==='employee-new'?'Add Employee':modal?.type==='employee'?'Edit Employee':modal?.type==='project'?'Edit Project':modal?.type==='company'?'Edit Company':modal?.type==='contact'?'Edit Contact':modal?.type==='followup'?'Edit Follow-up':'CRM'} onClose={()=>setModal(null)}>
      {(modal==='company'||modal?.type==='company')&&<CompanyForm data={modal.data} profile={profile} onSave={(x)=>save('companies',x,modal.data?.id)}/>} 
      {(modal==='contact'||modal?.type==='contact')&&<ContactForm data={modal.data} companies={companies} onSave={(x)=>save('contacts',x,modal.data?.id)}/>} 
      {(modal==='project'||modal?.type==='project')&&<ProjectForm data={modal.data} companies={companies} employees={employees} stages={stages} profile={profile} onSave={(x)=>save('projects',x,modal.data?.id)}/>} 
      {(modal==='followup'||modal?.type==='followup')&&<FollowupForm data={modal.data} projects={projects} employees={employees} profile={profile} onSave={(x)=>save('follow_ups',x,modal.data?.id)}/>} 
      {modal==='payment'&&<PaymentForm projects={projects} profile={profile} onSave={(x)=>save('payments',x)}/>} 
      {modal==='employee-new'&&<EmployeeForm isNew onSave={createEmployee}/>} {modal?.type==='employee'&&<EmployeeForm data={modal.data} onSave={(x)=>save('profiles',x,modal.data.id)}/>} 
    </Modal>}
  </div>
}

function Dashboard({isAdmin,projects,employees,expected,contractValue,collected,overdue,dueToday,onTab}){return <div className="content"><div className="hero"><div><h2>{isAdmin?'Executive Sales Overview':'My Sales Workspace'}</h2><p>EMDAD sales pipeline, project ownership, follow-ups and collections.</p></div><button className="primary" onClick={()=>onTab('projects')}>View projects →</button></div><div className="stats-grid"><Stat label="Active Projects" value={projects.filter(p=>!['closed_won','lost'].includes(p.sales_stage)).length}/><Stat label="Expected Pipeline" value={money(expected)}/><Stat label="Contract Value" value={money(contractValue)}/><Stat label="Collected" value={money(collected)}/><Stat label="Overdue Follow-ups" value={overdue.length}/><Stat label="Due Today" value={dueToday.length}/></div><div className="grid-2"><section className="panel"><div className="panel-head"><div><h3>Attention required</h3><span>Next actions for the team</span></div><button onClick={()=>onTab('followups')}>Open follow-ups →</button></div><div className="attention-list"><div className="attention danger"><b>{overdue.length}</b><div><strong>Overdue follow-ups</strong><small>Customer/project actions that need attention</small></div></div><div className="attention warning"><b>{dueToday.length}</b><div><strong>Due today</strong><small>Follow-ups scheduled today</small></div></div></div></section><section className="panel"><div className="panel-head"><div><h3>Team</h3><span>Active sales employees</span></div><button onClick={()=>isAdmin&&onTab('employees')}>View team →</button></div><div className="employee-cards">{employees.filter(e=>e.is_active).map(e=><div className="employee-card" key={e.id}><div className="avatar">{(e.full_name||'U').slice(0,1)}</div><div className="employee-card-main"><b>{e.full_name}</b><small>{projects.filter(p=>p.assigned_employee_id===e.id).length} projects</small></div></div>)}{!employees.length&&<Empty text="No employees yet."/>}</div></section></div></div>}

function Projects({projects,employees,isAdmin,stages,onNew,onEdit}){return <div className="content"><div className="toolbar"><div><h2>Projects</h2><p>Each project has one responsible employee.</p></div>{isAdmin&&<button className="primary" onClick={onNew}>+ New Project</button>}</div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Project</th><th>Company</th><th>Owner</th><th>Stage</th><th>Expected</th><th>Contract</th><th/></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><b>{p.project_name}</b><small className="table-sub">{p.project_type||'HVAC / MEP'}</small></td><td>{p.companies?.company_name||'—'}</td><td>{p.profiles?.full_name||'Unassigned'}</td><td><Badge tone={p.sales_stage==='lost'?'danger':p.sales_stage==='closed_won'?'success':'info'}>{p.stage_label}</Badge></td><td>{money(p.expected_value)}</td><td>{money(p.contract_value)}</td><td><button className="row-action" onClick={()=>onEdit(p)}>Edit</button></td></tr>)}{!projects.length&&<tr><td colSpan="7"><Empty/></td></tr>}</tbody></table></div></section></div>}

function Companies({companies,contacts,isAdmin,onNew,onEdit}){return <div className="content"><div className="toolbar"><div><h2>Companies</h2><p>One master company record for all projects and contacts.</p></div>{isAdmin&&<button className="primary" onClick={onNew}>+ New Company</button>}</div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Company</th><th>Type</th><th>Industry</th><th>Contacts</th><th/></tr></thead><tbody>{companies.map(c=><tr key={c.id}><td><b>{c.company_name}</b></td><td>{c.client_type||'—'}</td><td>{c.industry||'—'}</td><td>{contacts.filter(x=>x.company_id===c.id).length}</td><td>{isAdmin&&<button className="row-action" onClick={()=>onEdit(c)}>Edit</button>}</td></tr>)}{!companies.length&&<tr><td colSpan="5"><Empty/></td></tr>}</tbody></table></div></section></div>}

function Contacts({contacts,companies,onNew,onEdit}){return <div className="content"><div className="toolbar"><div><h2>Contacts</h2><p>Decision makers and project stakeholders.</p></div><button className="primary" onClick={onNew}>+ New Contact</button></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Name</th><th>Company</th><th>Title</th><th>Phone</th><th>Email</th><th/></tr></thead><tbody>{contacts.map(c=><tr key={c.id}><td><b>{c.contact_name}</b></td><td>{c.companies?.company_name||companies.find(x=>x.id===c.company_id)?.company_name||'—'}</td><td>{c.job_title||'—'}</td><td>{c.phone||'—'}</td><td>{c.email||'—'}</td><td><button className="row-action" onClick={()=>onEdit(c)}>Edit</button></td></tr>)}{!contacts.length&&<tr><td colSpan="6"><Empty/></td></tr>}</tbody></table></div></section></div>}

function Followups({followUps,projects,employees,isAdmin,onNew,onEdit}){const rows=[...followUps].sort((a,b)=>String(a.follow_up_date).localeCompare(String(b.follow_up_date)));return <div className="content"><div className="toolbar"><div><h2>Follow-ups</h2><p>Every project should have a clear next action.</p></div><button className="primary" onClick={onNew}>+ New Follow-up</button></div><div className="stats-grid three"><Stat label="Overdue" value={rows.filter(x=>x.follow_up_date&&x.follow_up_date.slice(0,10)<today()).length}/><Stat label="Due Today" value={rows.filter(x=>x.follow_up_date?.slice(0,10)===today()).length}/><Stat label="Total" value={rows.length}/></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Project</th><th>Employee</th><th>Date</th><th>Type</th><th>Notes</th><th/></tr></thead><tbody>{rows.map(x=>{const overdue=x.follow_up_date?.slice(0,10)<today();return <tr key={x.id}><td><b>{x.projects?.project_name||projects.find(p=>p.id===x.project_id)?.project_name||'—'}</b></td><td>{x.profiles?.full_name||employees.find(e=>e.id===x.employee_id)?.full_name||'—'}</td><td><Badge tone={overdue?'danger':'info'}>{dateText(x.follow_up_date)}</Badge></td><td>{x.follow_up_type_id||'—'}</td><td>{x.notes||'—'}</td><td><button className="row-action" onClick={()=>onEdit(x)}>Edit</button></td></tr>})}{!rows.length&&<tr><td colSpan="6"><Empty/></td></tr>}</tbody></table></div></section></div>}

function Collections({payments,projects,contracts,employees,profile,onNew}){const grouped=projects.map(p=>{const ps=payments.filter(x=>x.project_id===p.id);const collected=ps.reduce((s,x)=>s+Number(x.amount||0),0);const contract=Number(p.contract_value||contracts.find(c=>c.project_id===p.id)?.contract_value||0);return {p,collected,contract,remaining:Math.max(contract-collected,0)}}).filter(x=>x.contract>0||x.collected>0);return <div className="content"><div className="toolbar"><div><h2>Collections</h2><p>Collections are recorded and followed by the responsible employee.</p></div><button className="primary" onClick={onNew}>+ Record Collection</button></div><div className="stats-grid three"><Stat label="Contracted" value={money(grouped.reduce((s,x)=>s+x.contract,0))}/><Stat label="Collected" value={money(payments.reduce((s,x)=>s+Number(x.amount||0),0))}/><Stat label="Outstanding" value={money(grouped.reduce((s,x)=>s+x.remaining,0))}/></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Project</th><th>Owner</th><th>Contract</th><th>Collected</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>{grouped.map(x=><tr key={x.p.id}><td><b>{x.p.project_name}</b></td><td>{x.p.profiles?.full_name||'—'}</td><td>{money(x.contract)}</td><td>{money(x.collected)}</td><td><b>{money(x.remaining)}</b></td><td><Badge tone={x.remaining===0?'success':x.collected>0?'warning':'neutral'}>{x.remaining===0?'Fully Collected':x.collected>0?'Partially Collected':'Not Collected'}</Badge></td></tr>)}{!grouped.length&&<tr><td colSpan="6"><Empty text="No contracted projects or collections yet."/></td></tr>}</tbody></table></div></section></div>}

function Employees({employees,projects,followUps,payments,onNew,onEdit}){return <div className="content"><div className="toolbar"><div><h2>Employees</h2><p>Manage access and review individual performance.</p></div><button className="primary" onClick={onNew}>+ Add Employee</button></div><div className="employee-grid">{employees.map(e=>{const ps=projects.filter(p=>p.assigned_employee_id===e.id);const fs=followUps.filter(x=>x.employee_id===e.id);const col=payments.filter(x=>x.recorded_by===e.id).reduce((s,x)=>s+Number(x.amount||0),0);return <div className="performance-card" key={e.id}><div className="perf-top"><div className="avatar large">{(e.full_name||'U').slice(0,1)}</div><div><h3>{e.full_name}</h3><span>{e.position||'Sales Employee'}</span></div><Badge tone={e.is_active?'success':'danger'}>{e.is_active?'Active':'Inactive'}</Badge></div><div className="perf-metrics"><div><small>Projects</small><b>{ps.length}</b></div><div><small>Expected</small><b>{money(ps.reduce((s,p)=>s+Number(p.expected_value||0),0))}</b></div><div><small>Collected</small><b>{money(col)}</b></div><div><small>Follow-ups</small><b>{fs.length}</b></div></div><button className="secondary full" onClick={()=>onEdit(e)}>Edit access / role</button></div>})}{!employees.length&&<Empty text="No employees yet."/>}</div></div>}

function Reports({employees,projects,payments,followUps}){return <div className="content"><div className="toolbar"><div><h2>Reports</h2><p>Management view by employee.</p></div></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Projects</th><th>Expected</th><th>Collected</th><th>Follow-ups</th></tr></thead><tbody>{employees.map(e=><tr key={e.id}><td><b>{e.full_name}</b></td><td>{projects.filter(p=>p.assigned_employee_id===e.id).length}</td><td>{money(projects.filter(p=>p.assigned_employee_id===e.id).reduce((s,p)=>s+Number(p.expected_value||0),0))}</td><td>{money(payments.filter(p=>p.recorded_by===e.id).reduce((s,p)=>s+Number(p.amount||0),0))}</td><td>{followUps.filter(f=>f.employee_id===e.id).length}</td></tr>)}</tbody></table></div></section></div>}

function Modal({title,onClose,children}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={onClose}>×</button></div>{children}</div></div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Input({value,onChange,...props}){return <input value={value??''} onChange={e=>onChange(e.target.value)} {...props}/>}
function FormGrid({children,onSave}){return <form className="form-grid" onSubmit={e=>{e.preventDefault();onSave()}}>{children}<div className="form-actions"><button type="submit" className="primary">Save record</button></div></form>}
function CompanyForm({data,profile,onSave}){const [f,setF]=useState({name:'',industry:'',address:'',client_type:'',notes:'',...data});const u=(k,v)=>setF(x=>({...x,[k]:v}));return <FormGrid onSave={()=>onSave({...f,created_by:f.created_by||profile.id})}><Field label="Company Name *"><Input value={f.name} onChange={v=>u('name',v)} required/></Field><Field label="Client Type"><Input value={f.client_type||''} onChange={v=>u('client_type',v)}/></Field><Field label="Industry"><Input value={f.industry||''} onChange={v=>u('industry',v)}/></Field><Field label="Address"><Input value={f.address||''} onChange={v=>u('address',v)}/></Field><Field label="Notes"><textarea value={f.notes||''} onChange={e=>u('notes',e.target.value)}/></Field></FormGrid>}
function ContactForm({data,companies,onSave}){const [f,setF]=useState({company_id:'',full_name:'',job_title:'',phone:'',email:'',is_primary:false,...data});const u=(k,v)=>setF(x=>({...x,[k]:v}));return <FormGrid onSave={()=>onSave(f)}><Field label="Company *"><select value={f.company_id} onChange={e=>u('company_id',e.target.value)} required><option value="">Select company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></Field><Field label="Full Name *"><Input value={f.full_name} onChange={v=>u('full_name',v)} required/></Field><Field label="Job Title"><Input value={f.job_title||''} onChange={v=>u('job_title',v)}/></Field><Field label="Phone"><Input value={f.phone||''} onChange={v=>u('phone',v)}/></Field><Field label="Email"><Input value={f.email||''} onChange={v=>u('email',v)}/></Field></FormGrid>}
function ProjectForm({data,companies,employees,stages,profile,onSave}){const [f,setF]=useState({name:'',company_id:'',contact_id:null,assigned_employee_id:'',stage_id:stages[0]?.id||1,expected_value:0,contract_value:0,industry:'',description:'',project_type:null,...data});const u=(k,v)=>setF(x=>({...x,[k]:v}));return <FormGrid onSave={()=>onSave({...f,name:f.name,created_by:f.created_by||profile.id,expected_value:Number(f.expected_value||0),contract_value:Number(f.contract_value||0),assigned_employee_id:f.assigned_employee_id||null})}><Field label="Project Name *"><Input value={f.name||''} onChange={v=>u('name',v)} required/></Field><Field label="Company"><select value={f.company_id||''} onChange={e=>u('company_id',e.target.value)}><option value="">Select company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></Field><Field label="Employee"><select value={f.assigned_employee_id||''} onChange={e=>u('assigned_employee_id',e.target.value)}><option value="">Unassigned</option>{employees.filter(e=>e.is_active).map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></Field><Field label="Stage"><select value={f.stage_id} onChange={e=>u('stage_id',Number(e.target.value))}>{stages.map(s=><option key={s.id} value={s.id}>{s.name_ar||s.label}</option>)}</select></Field><Field label="Expected Value"><Input type="number" value={f.expected_value||0} onChange={v=>u('expected_value',v)}/></Field><Field label="Contract Value"><Input type="number" value={f.contract_value||0} onChange={v=>u('contract_value',v)}/></Field><Field label="Description"><textarea value={f.description||''} onChange={e=>u('description',e.target.value)}/></Field></FormGrid>}
function FollowupForm({data,projects,employees,profile,onSave}){const [f,setF]=useState({project_id:'',employee_id:profile.id,follow_up_type_id:1,follow_up_date:today(),notes:'',...data});const u=(k,v)=>setF(x=>({...x,[k]:v}));return <FormGrid onSave={()=>onSave({...f,employee_id:f.employee_id||profile.id,follow_up_date:new Date(`${f.follow_up_date}T09:00:00`).toISOString()})}><Field label="Project *"><select value={f.project_id} onChange={e=>u('project_id',e.target.value)} required><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.project_name}</option>)}</select></Field><Field label="Employee"><select value={f.employee_id||''} onChange={e=>u('employee_id',e.target.value)}>{employees.filter(e=>e.is_active).map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></Field><Field label="Date"><Input type="date" value={String(f.follow_up_date||today()).slice(0,10)} onChange={v=>u('follow_up_date',v)}/></Field><Field label="Type ID"><Input type="number" value={f.follow_up_type_id||1} onChange={v=>u('follow_up_type_id',Number(v))}/></Field><Field label="Notes"><textarea value={f.notes||''} onChange={e=>u('notes',e.target.value)}/></Field></FormGrid>}
function PaymentForm({projects,profile,onSave}){const [f,setF]=useState({project_id:'',amount:0,payment_date:today(),method:'Bank Transfer',reference_no:'',purpose:'collection'});const u=(k,v)=>setF(x=>({...x,[k]:v}));return <FormGrid onSave={()=>onSave({...f,amount:Number(f.amount||0),recorded_by:profile.id})}><Field label="Project *"><select value={f.project_id} onChange={e=>u('project_id',e.target.value)} required><option value="">Select project</option>{projects.filter(p=>Number(p.contract_value||0)>0).map(p=><option key={p.id} value={p.id}>{p.project_name}</option>)}</select></Field><Field label="Amount"><Input type="number" value={f.amount} onChange={v=>u('amount',v)} required/></Field><Field label="Payment Date"><Input type="date" value={f.payment_date} onChange={v=>u('payment_date',v)}/></Field><Field label="Method"><Input value={f.method} onChange={v=>u('method',v)}/></Field><Field label="Reference"><Input value={f.reference_no||''} onChange={v=>u('reference_no',v)}/></Field></FormGrid>}
function EmployeeForm({data,isNew,onSave}){const [f,setF]=useState({full_name:'',email:'',password:'',role:'employee',position:'',phone:'',is_active:true,...data});const u=(k,v)=>setF(x=>({...x,[k]:v}));return <FormGrid onSave={()=>onSave(isNew?{full_name:f.full_name,email:f.email,password:f.password,role:'employee',position:f.position,phone:f.phone,is_active:f.is_active}:{full_name:f.full_name,role:f.role,position:f.position,phone:f.phone,is_active:f.is_active})}><Field label="Full Name *"><Input value={f.full_name||''} onChange={v=>u('full_name',v)} required/></Field>{isNew&&<><Field label="Login Email *"><Input type="email" value={f.email||''} onChange={v=>u('email',v)} required/></Field><Field label="Initial Password *"><Input type="password" value={f.password||''} onChange={v=>u('password',v)} minLength={8} required/></Field></>}<Field label="Position"><Input value={f.position||''} onChange={v=>u('position',v)}/></Field><Field label="Phone"><Input value={f.phone||''} onChange={v=>u('phone',v)}/></Field><label className="check"><input type="checkbox" checked={!!f.is_active} onChange={e=>u('is_active',e.target.checked)}/> Account active</label></FormGrid>}
